language: scala
scala:
  - 2.9.3
  - 2.10.2
  - 2.10.3
before_install:
  - chmod +x gradlew
install:
  - true
before_script:
  - TERM=dumb ./gradlew setupCIWorkspace
script: TERM=dumb ./gradlew buildNeeded
